# -*- mode: python -*-

Import("env")

env.Library(
    target='lexer',
    source=[
        'lexer.cpp', 
    ]
)

env.CppUnitTest(
    target='lexer_test',
    source=[
        'lexer_test.cpp'
    ], 
    LIBDEPS=[
        'lexer'
    ]
)
