# -*- mode: python -*-

Import('env')

env.Library(
    target='ast_parser',
    source=[
        'ast_parser.cpp',
        'array_literal.cpp',
        'binary_operator.cpp',
        'nonterminal_node.cpp',
        'terminal_node.cpp',
        'identifier.cpp',
        'scope.cpp',
        'ternary_operator.cpp',
        'unary_operator.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/pipeline/document_value'
    ]
)

env.Library(
    target='lexer',
    source=[
        'lexer.cpp', 
    ]
)

env.CppUnitTest(
    target='ast_parser_test',
    source=[
        'ast_parser_test.cpp',
    ],
    LIBDEPS=[
        'ast_parser',
        'lexer'
    ],
)

env.CppUnitTest(
    target='lexer_test',
    source=[
        'lexer_test.cpp'
    ], 
    LIBDEPS=[
        'lexer'
    ]
)

env.CppUnitTest(
    target='evaluation_test',
    source=[
        'evaluation_test.cpp'
    ], 
    LIBDEPS=[
        'ast_parser', 
        'lexer',
        '$BUILD_DIR/mongo/bson/mutable/mutable_bson'
    ]
)
